name: Android CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Aura APK
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Java 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Grant Execute Permission
      - name: Grant Execute Permission
        run: chmod +x ./gradlew

      # Clean Project
      - name: Clean Project
        run: ./gradlew clean --no-daemon

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      # Upload APK Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aura-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
